# Generated by Django 4.2.9 on 2024-01-19 06:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CommoditiesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('price', models.FloatField(help_text='Price of each commodity.')),
                ('current_price', models.FloatField()),
                ('buy_date', models.DateField(help_text='Enter Date in YYYY-MM-DD format.')),
                ('total_assigned', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('functional', 'Functional'), ('nonfunctional', 'Non-functional')], default='functional', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='InventoryModel',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('depreciation_percent', models.IntegerField(default=10)),
            ],
        ),
        migrations.CreateModel(
            name='CommodityModel',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('assign_to', models.CharField(max_length=50)),
                ('commodity_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.commoditiesmodel')),
            ],
        ),
        migrations.AddField(
            model_name='commoditiesmodel',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.department'),
        ),
        migrations.AddField(
            model_name='commoditiesmodel',
            name='inventory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.inventorymodel'),
        ),
    ]
