# Generated by Django 4.2.9 on 2024-01-19 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commoditiesmodel',
            name='status',
        ),
        migrations.AddField(
            model_name='commoditymodel',
            name='status',
            field=models.CharField(choices=[('functional', 'Functional'), ('nonfunctional', 'Non-functional')], default='functional', max_length=20),
        ),
    ]
