# Generated by Django 4.2.9 on 2024-01-28 04:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AssignItemModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("item_id", models.CharField(max_length=20)),
                ("assign_to", models.CharField(blank=True, max_length=50)),
                (
                    "status",
                    models.CharField(
                        choices=[("Assigned", "Assigned"), ("In-Stock", "In-Stock")],
                        default="In-Stock",
                        max_length=20,
                    ),
                ),
                (
                    "functionality",
                    models.CharField(
                        choices=[
                            ("Functional", "Functional"),
                            ("Non-Functional", "Non-Functional"),
                        ],
                        default="Functional",
                        max_length=20,
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="inventory.department",
                    ),
                ),
                (
                    "nomenclature",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="inventory.nomenclaturemodel",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="AddRecordForm",
        ),
    ]
