# Generated by Django 4.2.9 on 2024-01-22 11:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0002_commoditymodel_inventory"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="commoditymodel",
            name="item",
        ),
    ]
