# Generated by Django 4.2.9 on 2024-01-31 04:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0002_assignitemmodel_delete_addrecordform"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assignitemmodel",
            name="status",
            field=models.CharField(
                choices=[("Assigned", "Assigned"), ("In-Stock", "In-Stock")],
                default="Assigned",
                max_length=20,
            ),
        ),
    ]
